/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAgentRegistry } from "./IAgentRegistry";
export type { IBulletinBoard } from "./IBulletinBoard";
