/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PriceConverterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "NATIVE_ASSET_DECIMALS"
      | "NATIVE_ASSET_PRICE_FEED"
      | "USDT_DECIMALS"
      | "USDT_PRICE_FEED"
      | "USD_DECIMALS"
      | "convertNativeAssetToUSD"
      | "convertNativeAssetToUSDT"
      | "convertUSDTToNativeAsset"
      | "convertUSDTToUSD"
      | "convertUSDToNativeAsset"
      | "convertUSDToUSDT"
      | "latestNativeAssetPriceInUSD"
      | "latestUSDTPriceInUSD"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "NATIVE_ASSET_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NATIVE_ASSET_PRICE_FEED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDT_PRICE_FEED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USD_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convertNativeAssetToUSD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertNativeAssetToUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertUSDTToNativeAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertUSDTToUSD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertUSDToNativeAsset",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertUSDToUSDT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestNativeAssetPriceInUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "latestUSDTPriceInUSD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "NATIVE_ASSET_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NATIVE_ASSET_PRICE_FEED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USDT_PRICE_FEED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USD_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertNativeAssetToUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertNativeAssetToUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertUSDTToNativeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertUSDTToUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertUSDToNativeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertUSDToUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestNativeAssetPriceInUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestUSDTPriceInUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceConverter extends BaseContract {
  connect(runner?: ContractRunner | null): PriceConverter;
  waitForDeployment(): Promise<this>;

  interface: PriceConverterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  NATIVE_ASSET_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  NATIVE_ASSET_PRICE_FEED: TypedContractMethod<[], [string], "view">;

  USDT_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  USDT_PRICE_FEED: TypedContractMethod<[], [string], "view">;

  USD_DECIMALS: TypedContractMethod<[], [bigint], "view">;

  convertNativeAssetToUSD: TypedContractMethod<
    [_assetAmount: BigNumberish],
    [bigint],
    "view"
  >;

  convertNativeAssetToUSDT: TypedContractMethod<
    [_assetAmount: BigNumberish],
    [bigint],
    "view"
  >;

  convertUSDTToNativeAsset: TypedContractMethod<
    [_usdtAmount: BigNumberish],
    [bigint],
    "view"
  >;

  convertUSDTToUSD: TypedContractMethod<
    [_usdtAmount: BigNumberish],
    [bigint],
    "view"
  >;

  convertUSDToNativeAsset: TypedContractMethod<
    [_usdAmount: BigNumberish],
    [bigint],
    "view"
  >;

  convertUSDToUSDT: TypedContractMethod<
    [_usdAmount: BigNumberish],
    [bigint],
    "view"
  >;

  latestNativeAssetPriceInUSD: TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _decimals: bigint }],
    "view"
  >;

  latestUSDTPriceInUSD: TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _decimals: bigint }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "NATIVE_ASSET_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NATIVE_ASSET_PRICE_FEED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDT_PRICE_FEED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USD_DECIMALS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertNativeAssetToUSD"
  ): TypedContractMethod<[_assetAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertNativeAssetToUSDT"
  ): TypedContractMethod<[_assetAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertUSDTToNativeAsset"
  ): TypedContractMethod<[_usdtAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertUSDTToUSD"
  ): TypedContractMethod<[_usdtAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertUSDToNativeAsset"
  ): TypedContractMethod<[_usdAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "convertUSDToUSDT"
  ): TypedContractMethod<[_usdAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "latestNativeAssetPriceInUSD"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _decimals: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestUSDTPriceInUSD"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { _price: bigint; _decimals: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
