[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@matterlabs/zksync-contracts/=lib/zksync-contracts/zksync-contracts/',
]
viaIR = true

[rpc_endpoints]
zksync_sepolia = "https://sepolia.era.zksync.dev"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
