[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@matterlabs/zksync-contracts/=lib/zksync-contracts/zksync-contracts/',
]
viaIR = true

[rpc_endpoints]
zksync-sepolia = "https://sepolia.era.zksync.dev"
