/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC6454,
  IERC6454Interface,
} from "../../../../contracts/token/interfaces/IERC6454";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "isTransferable",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC6454__factory {
  static readonly abi = _abi;
  static createInterface(): IERC6454Interface {
    return new Interface(_abi) as IERC6454Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IERC6454 {
    return new Contract(address, _abi, runner) as unknown as IERC6454;
  }
}
