/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { AgentRegistry } from "./AgentRegistry";
export type { BulletinBoard } from "./BulletinBoard";
