/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Agent } from "./Agent";
export type { Cryptopasta } from "./Cryptopasta";
export type { MissionLog } from "./MissionLog";
